# -*- coding: utf-8 -*-
"""Matrix Algebra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhP_Ui8N-bO23bTO7WD_QmjbHdWFIJw0

#Matrix and its Operations
"""

import numpy as np
a = np.array([1,2,3])
print(a)

import numpy as np
a = np.array([1,2,3])
a[0]= 4
print(a)

import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

import numpy as np
b = np.array([[1,2,3],[4,5,6]])
b[0,0] = 7
print(b)

import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

import numpy as np
d = np.full((2,2),7)
print(d)

import numpy as np
d = np.full((2,2),4)
print(d)

import numpy as np
e = np.eye(2)
print(e)

import numpy as np
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
h = np.diagonal(e)
print(h)

import numpy as np
g = np.zeros((2,2))
print(g)

import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)

import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e+g)

import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g)

import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e-g)

import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(g-e)